name: cubething

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: "${{secrets.GHCR_ACCESS}}"
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6.5.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Deploy the app
        uses: digitalocean/app_action/deploy@v
        env:
          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}2
        with:
          token: ${{ secrets.DO_ACCESS }}
